### ISSUE TITLE
Provide an option to disable cache

### ISSUE THREAD

**Issue by ChillarAnand** [niknah/veency#5]
Looks like veency is caching previous connection and when a new connection is started, it shows previous connection for few seconds. If there is an option to disable this, it would be great.

**Comment by niknah** [comment]
Which version are you referring to?  This is the old version of veency that only works in iOS 4.  Sorry.

**Comment by subho007** [comment]
@niknah sorry to hijack this thread. I just put my first compilable veency in my repo https://github.com/subho007/ios-vnc which is a fork of Saurik's veency

I am trying to add the `divideby screen` feature, but even after I went through the diff at http://pastie.org/8674111 I still couldn't implement it. A lot has changed, since you were using CoreSurface framework, but now it is using IOSurface since it was depricated. Can you help me here?

**Comment by niknah** [comment]
Sorry, here's my quick attempt at it.  I haven't tested or even tried to compile it cause I don't have the tools here.

The IOSurface... functions looks similar, they just added "IO" to the front.

Run "patch -p1 <divideby.txt"  to put it in.

[divideby.txt](https://github.com/niknah/veency/files/602135/divideby.txt)

**Comment by subho007** [comment]
@niknah this works 👍 you can close this issue
